import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import './style.css';
const $=s=>document.querySelector(s);
$('#app').innerHTML=`<header><div class="logo">ϟ</div><div><div class="brand">BATTERY CONCEPT</div><div class="subtitle">An interactive educational model</div></div><div class="header-right">PROCEDURAL GEOMETRY · APPROXIMATE DIMENSIONS</div></header><main class="workspace"><aside class="sidebar"><div class="side-head"><div class="eyebrow">Assembly browser</div><h1>Explore the concept</h1><p>A generic battery pack, built from simple shapes.</p><input id="search" class="search" placeholder="Search components" aria-label="Search components"><div class="small-row"><button id="all">Show all</button><button id="reset">Reset</button></div></div><div class="tree" id="tree"></div><div class="side-foot">No scans or source CAD meshes.<br>Illustrative arrangement, not a vehicle replica.<br><a href="./privacy.html">Privacy and hosting</a></div></aside><section class="stage" id="stage"><div class="stage-head"><div class="eyebrow">From cell to system</div><h2>How a battery fits together</h2><p>8 modules · 384 cells per module · 3,072 cells</p></div><div class="toolbar"><button id="labels" aria-pressed="false">Annotations</button><button id="fit">Fit view</button></div><div id="labels-layer"></div><div class="bottom-tools"><div class="view-buttons"><button data-view="iso">Perspective</button><button data-view="top">Top</button><button data-view="side">Side</button></div><div class="range-label"><label for="explode">Exploded view</label><output id="amount">0%</output></div><input type="range" id="explode" min="0" max="100" value="0"><div class="small-row"><button id="open" class="active">Open pack</button><button id="cells">Cells only</button></div></div></section><aside class="inspector" id="inspector"></aside></main>`;
const scene=new T.Scene();scene.background=new T.Color('#e9ede4');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));$('#stage').prepend(renderer.domElement);
const camera=new T.PerspectiveCamera(40,1,.01,50),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
scene.add(new T.HemisphereLight(0xffffff,0x7c8566,2.8));const light=new T.DirectionalLight(0xffffff,3);light.position.set(2,5,3);scene.add(light);
const parts=[];let selected=null,labels=false,opened=new Set(),explosion=0;
const palette={Structure:0x97a38d,Modules:0x58754e,Cells:0xb7cac6,Thermal:0x609baa,Electrical:0xc98741};
function add(name,group,geometry,position,dimensions,description,material,offset){const mesh=new T.Mesh(geometry,new T.MeshStandardMaterial({color:palette[group],roughness:.5,metalness:.2}));mesh.position.set(...position);scene.add(mesh);const p={name,group,mesh,base:mesh.position.clone(),dimensions,description,material,offset:new T.Vector3(...offset),visible:true};mesh.userData.part=p;parts.push(p);return p;}
function box(name,group,size,pos,description,material,offset=[0,.2,0]){return add(name,group,new T.BoxGeometry(...size),pos,size,description,material,offset)}
box('Lower enclosure','Structure',[2.08,.025,.88],[0,-.02,0],'Supports and protects the module assembly.','Aluminum, illustrative',[0,-.25,0]);
for(const z of [-.445,.445])box('Enclosure side rail '+(z>0?'A':'B'),'Structure',[2.08,.19,.02],[0,.065,z],'Represents the perimeter structure.','Aluminum, illustrative',[0,0,z*.5]);
for(const x of [-1.045,1.045])box('Enclosure end rail '+(x>0?'A':'B'),'Structure',[.02,.19,.91],[x,.065,0],'Closes the perimeter structure.','Aluminum, illustrative',[x*.3,0,0]);
const lid=box('Upper cover','Structure',[2.1,.015,.91],[0,.175,0],'Removable protective cover.','Aluminum, illustrative',[0,.85,0]);lid.visible=false;
const cellGeometry=new T.CylinderGeometry(.0105,.0105,.07,12);
for(let m=0;m<8;m++){
 const x=(m%4-1.5)*.49,z=(Math.floor(m/4)-.5)*.4;
 box(`Module ${m+1} tray`,'Modules',[.465,.012,.365],[x,0,z],'Groups cells into a serviceable conceptual assembly.','Aluminum, illustrative',[x*.2,-.08,z*.3]);
 box(`Module ${m+1} cooling plate`,'Thermal',[.45,.006,.35],[x,.08,z],'Illustrates a central liquid cooling interface between two cell layers. No flow simulation.','Aluminum, illustrative',[x*.2,.15,z*.3]);
 for(let layer=0;layer<2;layer++){
 const mesh=new T.InstancedMesh(cellGeometry,new T.MeshStandardMaterial({color:palette.Cells,metalness:.45,roughness:.35}),192);
 const dummy=new T.Object3D();let n=0;
 for(let row=0;row<12;row++)for(let col=0;col<16;col++){dummy.position.set((col-7.5)*.023+(row%2)*.0115,layer===0?.041:.119,(row-5.5)*.021);dummy.updateMatrix();mesh.setMatrixAt(n++,dummy.matrix)}
 mesh.position.set(x,0,z);mesh.computeBoundingBox();mesh.computeBoundingSphere();scene.add(mesh);
 const p={name:`Module ${m+1} ${layer?'upper':'lower'} cells`,group:'Cells',mesh,base:mesh.position.clone(),dimensions:[.3785,.07,.252],description:'192 illustrative cylindrical cells in a staggered 16 × 12 layer. Nominal cell envelope: 21 × 70 mm. Two layers per module.',material:'Mixed cell materials; chemistry unspecified',offset:new T.Vector3(x*.2,layer?.5:-.15,z*.3),visible:true};mesh.userData.part=p;parts.push(p);
 }
 box(`Module ${m+1} busbar`,'Electrical',[.4,.004,.012],[x,.159,z],'Symbolic current collector. Connections are illustrative and do not define an electrical circuit.','Copper, illustrative',[x*.2,.7,z*.3]);
}
box('Control electronics','Electrical',[.16,.04,.12],[-.96,.06,0],'Represents battery monitoring and control electronics. No live telemetry or BMS simulation.','PCB and housing, illustrative',[-.4,.35,0]);
const grid=new T.GridHelper(5,40,0xb9c5ad,0xd5ddcd);grid.position.y=-.04;scene.add(grid);
function inspect(){const p=selected;$('#inspector').innerHTML=p?`<div class="eyebrow">${p.group}</div><h2>${p.name}</h2><span class="tag">Concept geometry</span><p>${p.description}</p><div class="actions"><button id="isolate">Isolate</button><button id="focus">Focus</button></div><div class="property"><label>Approximate X × Y × Z (mm)</label><strong>${p.dimensions.map(d=>Math.round(d*1000)).join(' × ')}</strong><small>Authored design parameters, not measured vehicle data.</small></div><div class="property"><label>Illustrative material</label><strong>${p.material}</strong></div><div class="property"><label>Weight</label><strong>Not specified</strong><small>No validated mass or material-density calculation.</small></div>`:`<div class="eyebrow">About this model</div><h2>A concept, from scratch</h2><span class="tag">Public educational viewer</span><p>Explore an approximate enclosure, modular cell layers, cooling plates, and electrical hardware.</p><div class="property"><label>Illustrative cell count</label><strong>8 × 2 × 192 = 3,072</strong></div><div class="property"><label>Approximate pack envelope</label><strong>2,110 × 210 × 910 mm</strong></div><p>All dimensions and positions are authored for this demonstration. This does not represent a specific manufacturer, production battery, validated circuit, or service procedure.</p><p>Drag to orbit, scroll to zoom, and right-drag to pan. Select a component to learn its role.</p>`;if(p){$('#isolate').onclick=()=>{parts.forEach(q=>q.visible=q===p);refresh();tree();fit()};$('#focus').onclick=()=>fit('iso',new T.Box3().setFromObject(p.mesh))}}
function select(p){selected=p;if(p){opened=new Set([p.group]);$('#search').value=''}refresh();tree();inspect()}
function refresh(){parts.forEach(p=>{p.mesh.visible=p.visible;p.mesh.material.emissive.set(p===selected?0x44552a:0)});$('#labels-layer').innerHTML='';if(labels){const candidates=selected?[selected]:Object.keys(palette).map(g=>parts.find(p=>p.group===g&&p.visible));candidates.filter(p=>p?.visible).forEach(p=>{const e=document.createElement('button');e.className='label';e.textContent=p.name;e.onclick=()=>select(p);e.part=p;$('#labels-layer').append(e)})}}
function tree(){const q=$('#search').value.trim().toLowerCase();$('#tree').innerHTML=Object.keys(palette).map(g=>{const rows=parts.filter(p=>p.group===g&&p.name.toLowerCase().includes(q));return rows.length?`<details data-group="${g}" ${opened.has(g)?'open':''}><summary>${g}<span class="count">${rows.length}</span></summary>${rows.map(p=>`<div class="part"><input aria-label="Show ${p.name}" type="checkbox" data-check="${parts.indexOf(p)}" ${p.visible?'checked':''}><button data-part="${parts.indexOf(p)}">${p.name}</button></div>`).join('')}</details>`:''}).join('')||'<p>No matching components.</p>';$('#tree').querySelectorAll('summary').forEach(e=>e.onclick=event=>{event.preventDefault();const d=e.parentElement;opened=new Set(d.open?[]:[d.dataset.group]);$('#tree').querySelectorAll('details').forEach(x=>x.open=opened.has(x.dataset.group))});$('#tree').querySelectorAll('[data-part]').forEach(e=>e.onclick=()=>select(parts[+e.dataset.part]));$('#tree').querySelectorAll('[data-check]').forEach(e=>e.onchange=()=>{parts[+e.dataset.check].visible=e.checked;refresh()})}
function fit(view='iso',bounds){const b=bounds||parts.filter(p=>p.visible).reduce((b,p)=>b.union(new T.Box3().setFromObject(p.mesh)),new T.Box3());if(b.isEmpty())return;const c=b.getCenter(new T.Vector3()),s=b.getSize(new T.Vector3());const d=Math.max(s.x,s.y,s.z,.1)*1.7/Math.min(camera.aspect,1);const dir=view==='top'?new T.Vector3(0,1,.001):view==='side'?new T.Vector3(0,.01,1):new T.Vector3(1,1.5,1.5).normalize();camera.position.copy(c).addScaledVector(dir,d);controls.target.copy(c);controls.update()}
function preset(kind){parts.forEach(p=>p.visible=kind==='cells'?p.group==='Cells':kind==='all'||p!==lid);refresh();tree();fit()}
$('#all').onclick=()=>preset('all');$('#open').onclick=()=>preset('open');$('#cells').onclick=()=>preset('cells');$('#reset').onclick=()=>{selected=null;opened.clear();$('#search').value='';$('#explode').value=0;$('#explode').dispatchEvent(new Event('input'));preset('open');inspect()};$('#fit').onclick=()=>fit();$('#search').oninput=()=>{const q=$('#search').value.trim().toLowerCase();opened=new Set(q?parts.filter(p=>p.name.toLowerCase().includes(q)).map(p=>p.group):[]);tree()};$('#labels').onclick=e=>{labels=!labels;e.target.classList.toggle('active',labels);e.target.setAttribute('aria-pressed',labels);refresh()};$('#explode').oninput=e=>{explosion=+e.target.value/100;$('#amount').textContent=`${e.target.value}%`;parts.forEach(p=>p.mesh.position.copy(p.base).addScaledVector(p.offset,explosion))};document.querySelectorAll('[data-view]').forEach(e=>e.onclick=()=>fit(e.dataset.view));
let down;renderer.domElement.onpointerdown=e=>down=[e.clientX,e.clientY];renderer.domElement.onpointerup=e=>{if(e.button!==0||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);select(ray.intersectObjects(parts.filter(p=>p.visible).map(p=>p.mesh))[0]?.object.userData.part||null)};
new ResizeObserver(()=>{const w=$('#stage').clientWidth,h=$('#stage').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}).observe($('#stage'));
function animate(){requestAnimationFrame(animate);controls.update();$('#labels-layer').querySelectorAll('.label').forEach(e=>{const v=new T.Box3().setFromObject(e.part.mesh).getCenter(new T.Vector3()).project(camera);e.style.left=`${(v.x*.5+.5)*$('#stage').clientWidth}px`;e.style.top=`${(-v.y*.5+.5)*$('#stage').clientHeight}px`;e.style.display=Math.abs(v.z)>1?'none':'block'});renderer.render(scene,camera)}refresh();tree();inspect();requestAnimationFrame(()=>fit());animate();window.__concept={parts,select,preset};
