import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import './style.css';
import {buildModel} from './model.js';
const $=s=>document.querySelector(s);
$('#app').innerHTML=`<header><div class="logo">ϟ</div><div><div class="brand">BATTERY CONCEPT</div><div class="subtitle">An interactive educational model</div></div><div class="header-right">PROCEDURAL GEOMETRY · APPROXIMATE DIMENSIONS</div></header><main class="workspace"><aside class="sidebar"><div class="side-head"><div class="eyebrow">Assembly browser</div><h1>Explore the concept</h1><p>A generic battery pack, built from simple shapes.</p><input id="search" class="search" placeholder="Search components" aria-label="Search components"><div class="small-row"><button id="all">Show all</button><button id="reset">Reset</button></div></div><div class="tree" id="tree"></div><div class="side-foot">No scans or source CAD meshes.<br>Illustrative arrangement, not a vehicle replica.<br><a href="./privacy.html">Privacy and hosting</a></div></aside><section class="stage" id="stage"><div class="stage-head"><div class="eyebrow">From cell to system</div><h2>How a battery fits together</h2><p>201 components · 9 modules · 3,456 conceptual cells</p></div><div class="toolbar"><button id="labels" aria-pressed="false">Annotations</button><button id="fit">Fit view</button></div><div id="labels-layer"></div><div class="bottom-tools"><div class="view-buttons"><button data-view="iso">Perspective</button><button data-view="top">Top</button><button data-view="side">Side</button></div><div class="range-label"><label for="explode">Exploded view</label><output id="amount">0%</output></div><input type="range" id="explode" min="0" max="100" value="0"><div class="small-row"><button id="open" class="active">Open pack</button><button id="module">Module detail</button><button id="cells">Cells only</button><button id="catalog">Parts catalog</button></div></div></section><aside class="inspector" id="inspector"></aside></main>`;
const scene=new T.Scene();scene.background=new T.Color('#e9ede4');
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));$('#stage').prepend(renderer.domElement);
const camera=new T.PerspectiveCamera(40,1,.01,50),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
scene.add(new T.HemisphereLight(0xffffff,0x7c8566,2.8));const light=new T.DirectionalLight(0xffffff,3);light.position.set(2,5,3);scene.add(light);
const parts=buildModel(scene);let selected=null,labels=false,opened=new Set(),explosion=0;
const palette={Structure:0x97a38d,Modules:0x58754e,Cells:0xb7cac6,Thermal:0x609baa,Electrical:0xc98741};
const grid=new T.GridHelper(5,40,0xb9c5ad,0xd5ddcd);grid.position.y=-.04;scene.add(grid);
function inspect(){const p=selected;$('#inspector').innerHTML=p?`<div class="eyebrow">${p.group}</div><h2>${p.name}</h2><span class="tag">Concept geometry</span><p class="source-path">${p.hierarchy.join(" / ")}</p><p>${p.description}</p><div class="actions"><button id="isolate">Isolate</button><button id="focus">Focus</button></div><div class="property"><label>Approximate X × Y × Z (mm)</label><strong>${p.dimensions.map(d=>Math.round(d*1000)).join(' × ')}</strong><small>Authored design parameters, not measured vehicle data.</small></div><div class="property"><label>Illustrative material</label><strong>${p.material}</strong></div><div class="property"><label>Weight</label><strong>Not specified</strong><small>No validated mass or material-density calculation.</small></div>`:`<div class="eyebrow">About this model</div><h2>A concept, from scratch</h2><span class="tag">Public educational viewer</span><p>Explore an approximate enclosure, modular cell layers, cooling plates, and electrical hardware.</p><div class="property"><label>Illustrative cell count</label><strong>9 × 2 × 192 = 3,456</strong></div><div class="property"><label>Approximate pack envelope</label><strong>2,740 × 290 × 1,200 mm</strong></div><p>Component names and grouping follow the detailed workspace. All geometry, dimensions, and positions are authored for this demonstration. This does not represent a specific manufacturer, production battery, validated circuit, or service procedure.</p><p>Drag to orbit, scroll to zoom, and right-drag to pan. Select a component to learn its role.</p>`;if(p){$('#isolate').onclick=()=>{parts.forEach(q=>q.visible=q===p);refresh();tree();fit()};$('#focus').onclick=()=>{p.visible=true;refresh();tree();fit('iso',new T.Box3().setFromObject(p.mesh))}}}
function select(p){selected=p;if(p){opened=new Set(p.hierarchy.map((_,i)=>p.hierarchy.slice(0,i+1).join('/')));$('#search').value=''}refresh();tree();inspect()}
function refresh(){parts.forEach(p=>{p.mesh.visible=p.visible;p.mesh.material.emissive.set(p===selected?0x44552a:0)});$('#labels-layer').innerHTML='';if(labels){const candidates=selected?[selected]:Object.keys(palette).map(g=>parts.find(p=>p.group===g&&p.visible));candidates.filter(p=>p?.visible).forEach(p=>{const e=document.createElement('button');e.className='label';e.textContent=p.name;e.onclick=()=>select(p);e.part=p;$('#labels-layer').append(e)})}}
function tree(){
 const q=$('#search').value.trim().toLowerCase(),root={children:new Map(),items:[]};
 parts.filter(p=>(p.name+' '+p.hierarchy.join(' ')).toLowerCase().includes(q)).forEach(p=>{let node=root;for(const name of p.hierarchy){if(!node.children.has(name))node.children.set(name,{children:new Map(),items:[]});node=node.children.get(name)}node.items.push(p)});
 const count=node=>node.items.length+[...node.children.values()].reduce((n,c)=>n+count(c),0);
 function render(node,path=[]){return [...node.children].map(([name,child])=>{const next=[...path,name],id=next.join('/');return `<details data-group="${id}" ${opened.has(id)?'open':''}><summary>${name}<span class="count">${count(child)}</span></summary><div class="branch">${render(child,next)}</div></details>`}).join('')+node.items.map(p=>`<div class="part ${selected===p?'selected':''}"><input aria-label="Show ${p.name}" type="checkbox" data-check="${parts.indexOf(p)}" ${p.visible?'checked':''}><button data-part="${parts.indexOf(p)}">${p.name}</button></div>`).join('')}
 $('#tree').innerHTML=render(root)||'<p>No matching components.</p>';
 $('#tree').querySelectorAll('summary').forEach(e=>e.onclick=event=>{event.preventDefault();const d=e.parentElement,key=d.dataset.group;if(d.open){for(const id of [...opened])if(id===key||id.startsWith(key+'/'))opened.delete(id)}else{const parent=key.split('/').slice(0,-1).join('/');for(const id of [...opened])if(id.split('/').slice(0,-1).join('/')===parent)opened.delete(id);opened.add(key)}$('#tree').querySelectorAll('details').forEach(x=>x.open=opened.has(x.dataset.group))});
 $('#tree').querySelectorAll('[data-part]').forEach(e=>e.onclick=()=>select(parts[+e.dataset.part]));
 $('#tree').querySelectorAll('[data-check]').forEach(e=>e.onchange=()=>{parts[+e.dataset.check].visible=e.checked;refresh()});
}
function fit(view='iso',bounds){const b=bounds||parts.filter(p=>p.visible).reduce((b,p)=>b.union(new T.Box3().setFromObject(p.mesh)),new T.Box3());if(b.isEmpty())return;const c=b.getCenter(new T.Vector3()),s=b.getSize(new T.Vector3());const d=Math.max(s.x,s.y,s.z,.1)*1.7/Math.min(camera.aspect,1);const dir=view==='top'?new T.Vector3(0,1,.001):view==='side'?new T.Vector3(0,.01,1):new T.Vector3(1,1.5,1.5).normalize();camera.position.copy(c).addScaledVector(dir,d);controls.target.copy(c);controls.update()}
function preset(kind){$('#stage').classList.toggle('catalog',kind==='catalog');['open','module','cells','catalog'].forEach(id=>$('#'+id).classList.toggle('active',id===kind));parts.forEach(p=>p.mesh.scale.setScalar(1));$('#explode').disabled=kind==='catalog';if(kind==='catalog'){const entries=parts.filter(p=>p.key.startsWith('component'));parts.forEach(p=>p.visible=false);entries.forEach((p,i)=>{p.visible=true;p.mesh.scale.setScalar(.3/Math.max(...p.dimensions));p.mesh.position.set((i%12-5.5)*.43,.12,Math.floor(i/12)*.43-3.4)});$('#stage .stage-head p').textContent='201 components · Individually scaled for inspection';refresh();tree();fit('top');camera.position.sub(controls.target).multiplyScalar(1.4).add(controls.target);controls.update();return}$('#stage .stage-head p').textContent='201 components · 9 modules · 3,456 conceptual cells';parts.forEach(p=>p.mesh.position.copy(p.base).addScaledVector(p.offset,explosion));parts.forEach(p=>p.visible=kind==='cells'?p.group==='Cells':kind==='module'?p.detail&&!p.cover:kind==='all'||!p.cover);refresh();tree();fit()}
$('#all').onclick=()=>preset('all');$('#open').onclick=()=>preset('open');$('#cells').onclick=()=>preset('cells');$('#catalog').onclick=()=>preset('catalog');$('#module').onclick=()=>preset('module');$('#reset').onclick=()=>{selected=null;opened.clear();$('#search').value='';$('#explode').value=0;$('#explode').dispatchEvent(new Event('input'));preset('open');inspect()};$('#fit').onclick=()=>fit();$('#search').oninput=()=>{const q=$('#search').value.trim().toLowerCase();opened=new Set(q?parts.filter(p=>(p.name+' '+p.hierarchy.join(' ')).toLowerCase().includes(q)).flatMap(p=>p.hierarchy.map((_,i)=>p.hierarchy.slice(0,i+1).join('/'))):[]);tree()};$('#labels').onclick=e=>{labels=!labels;e.target.classList.toggle('active',labels);e.target.setAttribute('aria-pressed',labels);refresh()};$('#explode').oninput=e=>{explosion=+e.target.value/100;$('#amount').textContent=`${e.target.value}%`;parts.forEach(p=>p.mesh.position.copy(p.base).addScaledVector(p.offset,explosion))};document.querySelectorAll('[data-view]').forEach(e=>e.onclick=()=>fit(e.dataset.view));
let down;renderer.domElement.onpointerdown=e=>down=[e.clientX,e.clientY];renderer.domElement.onpointerup=e=>{if(e.button!==0||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);select(ray.intersectObjects(parts.filter(p=>p.visible).map(p=>p.mesh))[0]?.object.userData.part||null)};
new ResizeObserver(()=>{const w=$('#stage').clientWidth,h=$('#stage').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}).observe($('#stage'));
function animate(){requestAnimationFrame(animate);controls.update();$('#labels-layer').querySelectorAll('.label').forEach(e=>{const v=new T.Box3().setFromObject(e.part.mesh).getCenter(new T.Vector3()).project(camera);e.style.left=`${(v.x*.5+.5)*$('#stage').clientWidth}px`;e.style.top=`${(-v.y*.5+.5)*$('#stage').clientHeight}px`;e.style.display=Math.abs(v.z)>1?'none':'block'});renderer.render(scene,camera)}refresh();tree();inspect();requestAnimationFrame(()=>fit());animate();window.__concept={parts,select,preset};
